version: "3.9"
services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=fintech
    volumes:
      - "./postgres_data_mount:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"

  ingest_database:
    build: .
    image: data_m2:python3.11
    depends_on:
      - pgdatabase
    restart: on-failure
    volumes:
      - ./src:/app/src
      - ./data:/app/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    depends_on:
      - pgdatabase
